import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-organ-transplant-case-rate-reconciliation",
  "engine": "recovery",
  "title": "Organ Transplant Case-Rate Reconciliation",
  "shortTitle": "Organ Transplant Case-Rate Reconciliation",
  "tagline": "Quantify, recover, and prevent financial leakage through organ transplant case-rate reconciliation",
  "industry": "Transplant Revenue Integrity",
  "uiPort": 4639,
  "apiPort": 5639,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Organ Transplant Case-Rate Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "expectedAmount",
    "actualLabel": "Payer Paid Amount",
    "expectedLabel": "Contract-Supported Case Revenue",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Organ Transplant Case-Rate Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("payer-transplant-contract-library","OTC01","Payer transplant contract library","Execute payer transplant contract library using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed payer transplant contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Payer transplant contract library Reference","text","OTC01-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("patient-case-registry","OTC02","Patient case registry","Execute patient case registry using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed patient case registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Patient case registry Reference","text","OTC02-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("evaluation-phase-tracking","OTC03","Evaluation phase tracking","Execute evaluation phase tracking using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed evaluation phase tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Evaluation phase tracking Reference","text","OTC03-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("organ-acquisition-cost","OTC04","Organ acquisition cost","Execute organ acquisition cost using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed organ acquisition cost decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Organ acquisition cost Reference","text","OTC04-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("donor-procurement-expense","OTC05","Donor procurement expense","Execute donor procurement expense using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed donor procurement expense decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Donor procurement expense Reference","text","OTC05-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("case-rate-episode-definition","OTC06","Case-rate episode definition","Execute case-rate episode definition using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed case-rate episode definition decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Case-rate episode definition Reference","text","OTC06-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("included-service-validation","OTC07","Included service validation","Execute included service validation using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed included service validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Included service validation Reference","text","OTC07-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("excluded-service-validation","OTC08","Excluded service validation","Execute excluded service validation using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed excluded service validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Excluded service validation Reference","text","OTC08-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("outlier-stop-loss-calculation","OTC09","Outlier stop-loss calculation","Execute outlier stop-loss calculation using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed outlier stop-loss calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Outlier stop-loss calculation Reference","text","OTC09-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("professional-facility-reconciliation","OTC10","Professional facility reconciliation","Execute professional facility reconciliation using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed professional facility reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Professional facility reconciliation Reference","text","OTC10-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("travel-lodging-benefit","OTC11","Travel lodging benefit","Execute travel lodging benefit using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed travel lodging benefit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Travel lodging benefit Reference","text","OTC11-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("claim-remittance-ingestion","OTC12","Claim remittance ingestion","Execute claim remittance ingestion using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed claim remittance ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Claim remittance ingestion Reference","text","OTC12-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("underpayment-detection","OTC13","Underpayment detection","Execute underpayment detection using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed underpayment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Underpayment detection Reference","text","OTC13-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("payer-appeal-workflow","OTC14","Payer appeal workflow","Execute payer appeal workflow using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed payer appeal workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Payer appeal workflow Reference","text","OTC14-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]}),
feature("program-payer-analytics","OTC15","Program payer analytics","Execute program payer analytics using payer transplant contracts, patient cases, evaluation, organ acquisition, donor expenses, case-rate episodes, included and excluded services, outliers, stop-loss, claims, remittances, and appeals.","Produce a governed program payer analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Transplant Center / Patient Case","text","Transplant Center / Patient Case · Standard Case"],["caseReference","Program payer analytics Reference","text","OTC15-2026-001"],["paidAmount","Payer Paid Amount","currency",1308000],["expectedAmount","Contract-Supported Case Revenue","currency",1543440],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Payer transplant contract library case","Patient case registry case","Evaluation phase tracking case","Organ acquisition cost case","Donor procurement expense case"]})
]);
